version: '3.8'
name: bookoracle

services:
  bookoracle:
    container_name: bookoracle
    build: .
    ports:
      - "5054:5054"
    volumes:
      # Custom data directory on Ubuntu server
      - ../data/bookoracle:/app/data
    environment:
      # Security - MUST be set via .env file or environment
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      
      # Application settings
      - TIMEZONE=${TIMEZONE:-UTC}
      - WORKERS=${WORKERS:-4}
    restart: unless-stopped
