version: '3.8'
name: bookoracle

services:
  backend:
    container_name: bookoracle-backend
    build: .
    ports:
      - "5054:5054"   # Host Nginx proxies /api and /static to this
    volumes:
      - bookoracle_data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - TIMEZONE=${TIMEZONE:-UTC}
      - WORKERS=${WORKERS:-4}
      # Mail settings for password recovery
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5054/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: bookoracle-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3505:80"     # Host Nginx proxies / to this (SPA)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  bookoracle_data:
    driver: local
